### ISSUE TITLE
Adding Comments

### ISSUE THREAD

**Issue by MintBlast** [selgesel/godot-third-person-controller#1]
Hi, 

Just checking your code and applying them into my game but the problem is that I don't know how the code works. I have also tested the demo you made and I want to have the same controls as yours the problem is that I don't how every function and bits of your code work.

Perhaps adding comments in your code would work and it might helpful. If it's too much to ask, that is ok. I'll dissect the code as much as I can. Thanks.

**Comment by selgesel** [comment]
Hey, thanks for the comment! That's a very reasonable suggestion (and frankly should've been there from the get go), so I've added in a bunch of comments in the latest commit (f011ad468f90b11c59b61545c939d6e3f33eaa09), I hope they're useful.

I also realized that I didn't mention this in the [README](https://github.com/selgesel/godot-third-person-controller/blob/master/README.md) but this repo is actually a complementary to a video series I'm making. When implementing something I like to replicate stuff by coding along videos, so to allow others to do the same with my videos I try to explain everything in the code in detail. If you like that kind of stuff you might want to check them out: https://www.youtube.com/playlist?list=PLlT0CCZ8Yw0mcxG_D_sSA-Imnc5tiR4tx

Thanks again!

**Comment by MintBlast** [comment]
Hi,

Thanks for acknowledging the issue I've pointed out. I'll give your code a go since I'm still pulling my hair out since most tutorials either have a feature where the character only faces the camera's direction (mostly suitable for Third Person Shooters). Your controller is perfect for me and once again I'll give it a go and perhaps modify it. I'll also check out the video series to get a full understanding of how the controller works since I'm new to Godot.

Thanks and keep it up <3
